### ISSUE TITLE
Remove CM -> CR migration code

### ISSUE THREAD

**Issue by rollandf** [Mellanox/nvidia-k8s-ipam#30]
AS part of PR #24 , a migration flow has been added to support reading configuration from ConfigMap and allocations from Nodes Annotations and create IPPool CR accordingly.

This code should be removed in the next release.

**Comment by ykulazhenkov** [comment]
The migration logic for the node part was introduced in https://github.com/Mellanox/nvidia-k8s-ipam/pull/27. This logic should be removed as well.
