### ISSUE TITLE
[CNI] cache host-local config in CMD ADD call and use it in CHECK, DEL calls

### ISSUE THREAD

**Issue by adrianchiris** [Mellanox/nvidia-k8s-ipam#7]
### What happened?
If ip-block changes for the pool/network after CMD ADD was called, then, in CMD DEL / CHECK host-local CNI will be called with new parameters, this may cause unexpected behaviour with host-local CNI.

### What did you expect to happen?
host-local CNI should be called with same params as in CMD ADD call for the container, network,  interface

**Comment by adrianchiris** [comment]
I need to check how this manifests with CNI

But generally id i think its a correct beaviour that host-local CNI is called with original parameters from CMD ADD in  CMD CHECK/DEL.

**Comment by ykulazhenkov** [comment]
This issue was fixed as a part of #22. Closing.

**Comment by ykulazhenkov** [comment]
We are not using host-local IPAM anymore. The new built-in implementation has no such limitation.
